spring:
  datasource:
    url: jdbc:mysql://47.101.42.169:3306/db_oss_service?characterEncoding=utf8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: user_oss
    password: IeP6aLE517pmyEwZ
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql

  redis:
    database: 1
    # Redis服务器地址
    host: 10.0.101.144
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: seassoon13579
    timeout: 2000ms

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.berry.oss.core.entity,com.berry.oss.security.core.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
  global-config:
    sql-parser-cache: true


# logback set path
logging:
  config: classpath:logback/logback.xml
  level:
    root: INFO
    com.berry.oss: DEBUG
  path: ./log
  file:
    max-history: 30

global:
  # 单机模式(单机模式没用数据冗余)
  singleton: true
  hotDataCache: false
  dataPath: ./store
  # 本机 服务地址
  serverAddress: http://10.0.102.250:8077
  httpPort: 7077
  mail:
    from: berry_cooper@163.com
    baseUrl:

