spring:
  security:
    user:
      name: berry
      password: berry123
  datasource:
    url: jdbc:mysql://47.101.42.169:3306/db_oss_service_dev?characterEncoding=utf8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: berry
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql

  redis:
    database: 6
    host: 47.101.42.169
    port: 6379
    password:
    timeout: 2000ms

#  cloud:
#    consul:
#      discovery:
#        enabled: true
#        health-check-interval: 10s
#        health-check-url: http://127.0.0.1:${server.port}/actuator/health
#        instance-id: ${spring.application.name}:127.0.0.1:${server.port}
#        port: ${server.port}
#        service-name: ${spring.application.name}
#        tags: dev
#      enabled: true
#      host: 127.0.0.1
#      port: 8500

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.berry.oss.core.entity,com.berry.oss.security.core.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
  # 开启 SQL 解析缓存注解生效
  global-config:
    sql-parser-cache: true


# logback set path
logging:
  config: classpath:logback/logback.xml
  level:
    root: INFO
    com.berry.oss: DEBUG
  path: ./logs
  file:
    max-history: 30

global:
  # 单机模式(单机模式没用数据冗余)
  singleton: true
  hotDataCache: true
  dataPath: ./store
  # 本机 服务地址
  serverAddress: http://127.0.0.1:${server.port}
  httpPort: 7077
  mail:
    from: berry_cooper@163.com
    baseUrl:

